{application,dtask,
             [{description,"Distributed task executor"},
              {vsn,"0.1"},
              {registered,[]},
              {included_applications,[gen_leader]},
              {applications,[kernel,stdlib]},
              {mod,{dtask_app,[]}},
              {env,[]},
              {modules,[dtask,dtask_app,dtask_node_list,dtask_srv,dtask_sup,
                        dtask_timer]}]}.
